version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: api_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    environment:
      POSTGRES_DB: api_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
